name: test_django
on: [push]
jobs:
  kodjaz:
    runs-on: ubuntu-latest
    # Service containers to run with `kodjaz`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --name postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'
          cache: 'pip'
          cache-dependency-path: '**/requirements_dev.txt'
      - name: Prepare DB
        run: docker exec postgres bash -c "PGPASSWORD=postgres psql -U postgres -c \"create role postgres with password 'postgres'\""
      - name: Install dependencies
        run: pip install -r requirements/requirements_dev.txt # install all our dependencies for the project
      - name: Create a dummy env fille
        run: cp env_template .env
      - run: python manage.py test
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
