name: test_django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  kodjaz:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'  
      - run: pip install -r requirements/requirements_dev.txt # install all our dependencies for the project
      - run: pytest .
